CREATE TABLE `ProgressSoft`.`INVALID_DEALS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DEAL_ID` VARCHAR(45) NOT NULL,
  `FROM_CURRENCY` VARCHAR(3) NULL,
  `TO_CURRENCY` VARCHAR(3) NULL,
  `DEAL_TIMESTAMP` VARCHAR(32) NULL,
  `AMOUNT` DECIMAL(20,4) NULL,
  `FILE_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));

