CREATE TABLE `ProgressSoft`.`LOADED_FILES` (
  `FILE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FILE_NAME` VARCHAR(511) NOT NULL,
  PRIMARY KEY (`FILE_ID`),
  UNIQUE INDEX `FILE_ID_UNIQUE` (`FILE_ID` ASC),
  UNIQUE INDEX `FILE_NAME_UNIQUE` (`FILE_NAME` ASC));

